# Unique name for this workflow
name: Salesforce DX (scratch org)

# Definition when the workflow should run
on:
  pull_request:
    branches:
      - master

# Jobs to be executed
jobs:
  scratch-org-test:
    runs-on: ubuntu-latest
    steps:
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      # Checkout the code in the pull request
      - name: "Checkout source code"
        uses: actions/checkout@v2

      # Store secret for dev hub
      - name: "Populate auth file with PROD_SFDX_URL secret"
        shell: bash
        run: "echo ${{ secrets.PROD_SFDX_URL}} > ./PROD_SFDX_URL.txt"

      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        run: "sfdx force:auth:sfdxurl:store -f ./PROD_SFDX_URL.txt -a devhub -d"

      # Create scratch org
      - name: "Create scratch org"
        run: "sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1"

      # Install rstk plugin used to install multiple packages only by version number
      - name: "Install rstk plugin"
        run: "echo y | sfdx plugins:install rstk-sfdx-package-utils@0.1.12"

      # Install packages this repo is dependant on
      - name: "Install dependant packages"
        run: "sfdx rstk:package:dependencies:install -u scratch-org -w 20 --noprecheck -k '1:$SFDX_PACKAGE_KEY 2:$SFDX_PACKAGE_KEY 3:$SFDX_PACKAGE_KEY 4:$SFDX_PACKAGE_KEY 5:$SFDX_PACKAGE_KEY'"

      # Deploy source to scratch org
      - name: "Push source to scratch org"
        run: "sfdx force:source:push"

      # Run Apex tests in scratch org
      - name: "Run Apex tests"
        run: "sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20"

      # Housekeeping
      - name: "Delete scratch org"
        if: always()
        run: "sfdx force:org:delete -p -u scratch-org"
